### ISSUE TITLE
Subject changes for replies

### ISSUE THREAD

**Issue by osresearch** [NattyNarwhal/LobstersNntp#1]
trn4 works, with some mimetype formatting issues:

![image](https://user-images.githubusercontent.com/3068843/107940515-a1758100-6f88-11eb-9ec3-459d488a8c8f.png)

Followups have a different subject, so they are shown as "`Reply to skkda`" in the article overview and have a different subject marker (`[2]`) in the threaded view.

**Comment by NattyNarwhal** [comment]
What's trn4's criteria for subject names and threading? Most clients I've seen just use `References`. I know Xnews will just collapse the repeated subject names into ellipses, but still properly thread them.

**Comment by osresearch** [comment]
The threading works properly based on the `References` headers -- you can see the tree view in the upper right corner.  The `(1)` means that the message has the first subject line (and also that it has been read), the `[2]` means that the message has a different subject (and that it has not been read yet).

When reading a thread it isn't too much of a problem, although in the message selector screen it looks like this if the first message has not yet been read:
```
g+calvin            1  NattyNarwhal/LobstersNntp: Lobsters NNTP gateway
  calvin            2  >Reply to skkkda
  technetium 
```

If the first message in the thread has been read, then the message selector screen only shows the `Reply to` subject line. This makes it hard to know which original post they belong to:

```
e+calvin            2  >Reply to skkkda
  technetium      
```

**Comment by NattyNarwhal** [comment]
Ah, that explains a lot. When I insert the comments, they're done w/o a reference to the stories, but I suppose I can (pull up the story|provide it when inserting) to properly mangle the subject.

**Comment by osresearch** [comment]
![image](https://user-images.githubusercontent.com/3068843/107982105-bde2df00-6fc3-11eb-948c-2eb3d898e893.png)

Looks good in both article selector and tree view.  mimetypes are still my problem.

**Comment by NattyNarwhal** [comment]
Hmm, I do declare the mime-type properly (`text/html`, UTF-8). I'm guessing older clients don't support it, so I'll have to put some quoted-printable in there, strip the HTML, and provide the HTML as a MIME attachment?

**Comment by NattyNarwhal** [comment]
I put the MIME stuff into #3.
